spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:
  datasource:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: debug

#  sql:
#    init:
#      data-locations: classpath:person.sql
#  jpa:
#    defer-datasource-initialization: true